name: portfolio
description: Personal Portfolio

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.3
  zoomable_image: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/certificates/
    - assets/project_images/
    - assets/skills_icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-Medium.ttf
    - family: Jura
      fonts:
        - asset: fonts/Jura/Jura-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
